### PR TITLE
Fix swap direction of search results on each request

### PR DESCRIPTION
**Pull request by carlwoodward**

### CODE REVIEW

**Comment by carlwoodward** [comment]
Please merge. This is the best PR ever!
 
https://media.giphy.com/media/cFkiFMDg3iFoI/200w_d.gif

**Comment by carlwoodward** [comment]
Coding

**Comment by carlwoodward** [comment]
This is fine

**Comment by brucewoodward** [comment]
Work has been completed against the dev branch to fix and refactor the search code. Thanks for bring this to my attention.

**Pull request closed without merging**
